"""
panopticon_py/verification/pipeline_alert.py

RVF — Regular Verification Framework
Threshold checker + Alert dataclass.

Checks a PipelineSnapshot against shadow/production thresholds.
Generates Alert objects with severity, layer, message, value, threshold.
"""

from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime, timezone
from typing import Optional

from .pipeline_health import PipelineSnapshot

THRESHOLDS = {
    # Shadow mode (PANOPTICON_SHADOW=1) — relaxed for calibration
    "shadow": {
        "l1_tick_rate_per_min_min": 0.0,       # T1 markets may be quiet overnight
        "l1_entropy_fires_per_window_min": 0,   # Allow 0 during calibration
        "l4_live_trades_max": 0,               # CRITICAL if > 0
        "l5_wallet_obs_per_window_min": 1,     # Must see SOME wallet activity
    },
    # Production mode — strict
    "production": {
        "l1_tick_rate_per_min_min": 2.0,
        "l1_entropy_fires_per_window_min": 1,
        "l4_live_trades_max": 0,
        "l5_wallet_obs_per_window_min": 5,
    },
}


@dataclass
class Alert:
    """A single alert generated by the threshold checker."""
    severity: str       # "INFO", "WARN", "CRITICAL"
    layer: str          # "L1", "L2", "L3", "L4", "L5", "SYSTEM"
    message: str
    value: float
    threshold: float
    ts_utc: str


def check_snapshot(
    snap: PipelineSnapshot,
    mode: str = "shadow",
) -> list[Alert]:
    """
    Check a PipelineSnapshot against thresholds for the given mode.
    Returns a list of Alerts (may be empty).
    """
    alerts: list[Alert] = []
    t = THRESHOLDS.get(mode, THRESHOLDS["shadow"])
    now = datetime.now(timezone.utc).isoformat()

    # ── CRITICAL: LIVE trades in shadow mode ─────────────────────────────
    if snap.l4_live_trades > t["l4_live_trades_max"]:
        alerts.append(Alert(
            "CRITICAL",
            "L4",
            f"LIVE trades detected: {snap.l4_live_trades} — "
            "Invariant 5.1 violation",
            float(snap.l4_live_trades),
            0.0,
            now,
        ))

    # ── WARN: no wallet observations ─────────────────────────────────────
    if snap.l5_wallet_obs_written < t["l5_wallet_obs_per_window_min"]:
        alerts.append(Alert(
            "WARN",
            "L5",
            f"wallet_observations={snap.l5_wallet_obs_written} "
            f"in {snap.window_minutes}min window",
            float(snap.l5_wallet_obs_written),
            float(t["l5_wallet_obs_per_window_min"]),
            now,
        ))

    # ── INFO: pipeline rate ────────────────────────────────────────────────
    alerts.append(Alert(
        "INFO",
        "L1",
        (
            f"tick_rate={snap.l1_tick_rate_per_min}/min | "
            f"entropy_fires={snap.l1_entropy_fires} | "
            f"kyle_progress={snap.kyle_accumulation_rate * 100:.1f}% | "
            f"paper_trades={snap.l4_paper_trades} | "
            f"pipeline_pass={snap.pipeline_pass_rate:.2%}"
        ),
        snap.l1_tick_rate_per_min,
        t["l1_tick_rate_per_min_min"],
        now,
    ))

    # ── WARN: entropy fires but 0 paper trades (L3/L4 gate blocking) ──────
    if snap.data_staleness_flag and snap.l1_entropy_fires > 0:
        alerts.append(Alert(
            "WARN",
            "L3/L4",
            (
                f"EV gate may be blocking all signals: "
                f"entropy_fires={snap.l1_entropy_fires} "
                f"but paper_trades={snap.l4_paper_trades} — "
                "check fast_gate.py thresholds in shadow mode"
            ),
            0.0,
            1.0,
            now,
        ))

    # ── WARN: kyle accumulation stalled ──────────────────────────────────
    if snap.kyle_accumulation_rate < 0.1 and snap.window_minutes >= 5:
        alerts.append(Alert(
            "WARN",
            "L1",
            f"kyle_accumulation={snap.kyle_accumulation_rate:.2%} "
            "(target: 500 samples) — "
            "T1 markets may be low-volume or subscription gap",
            snap.kyle_accumulation_rate,
            0.1,
            now,
        ))

    return alerts