"""
Execution reason code constants.
All execution_records.reason values must use these constants.
"""

REASON_PASS = "PASS"
REASON_LOW_EV = "LOW_EV"
REASON_GHOST_LIQ = "GHOST_LIQ"
REASON_KELLY_CAP = "KELLY_CAP"
REASON_NO_ENTITY = "NO_ENTITY"
REASON_PING_ABORT = "PING_ABORT"
REASON_DRY_RUN = "DRY_RUN"
REASON_CLOB_REJECT = "CLOB_REJECT"

REASON_NETWORK_LATENCY_BREAKER = "NETWORK_LATENCY_BREAKER"
REASON_DEGRADED_AND_EV_NOT_ENOUGH = "DEGRADED_AND_EV_NOT_ENOUGH"
REASON_L2_TIMEOUT_DEGRADED = "L2_TIMEOUT_DEGRADED"
REASON_SLIPPAGE_TOLERANCE_EXCEEDED = "SLIPPAGE_TOLERANCE_EXCEEDED"
REASON_NON_POSITIVE_TIME_ADJUSTED_EV = "NON_POSITIVE_TIME_ADJUSTED_EV"

# signal_engine.py reasons
REASON_INSUFFICIENT_CONSENSUS = "INSUFFICIENT_CONSENSUS"
REASON_NO_PRICE_DATA = "NO_PRICE_DATA"
REASON_KELLY_DEGRADED_PREFIX = "KELLY_DEGRADED:"
# D121: T1 short-circuit — Kyle λ computed separately, no consensus path
REASON_T1_SHORT_CIRCUIT = "T1_SHORT_CIRCUIT"

ALL_REASONS = {
    REASON_PASS,
    REASON_LOW_EV,
    REASON_GHOST_LIQ,
    REASON_KELLY_CAP,
    REASON_NO_ENTITY,
    REASON_PING_ABORT,
    REASON_DRY_RUN,
    REASON_CLOB_REJECT,
    REASON_NETWORK_LATENCY_BREAKER,
    REASON_DEGRADED_AND_EV_NOT_ENOUGH,
    REASON_L2_TIMEOUT_DEGRADED,
    REASON_SLIPPAGE_TOLERANCE_EXCEEDED,
    REASON_NON_POSITIVE_TIME_ADJUSTED_EV,
}
